import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { User } from './user';
import { map } from 'rxjs/operators';

//Headers for requests sent to the API
const httpOptions = {
  headers: new HttpHeaders({ 'Content-Type': 'application/json' })
};

@Injectable({
  providedIn: 'root'
})
export class ApiService {
  //API URL
  public api = "https://mgr-restapi.herokuapp.com";

  //For API local testing
  //public api = "http://localhost:8082"
  
  constructor(
    private http: HttpClient
  ) { }

  //--------------------------------- USER INFORMATION REQUESTS ---------------------------------

  //GET: /users (returns all users information except for password)
  getUsers() {

    return this.http.get<User[]>(`${this.api}/users`);
  }

  //GET: /users/:userid (return single user information except for password)
  getUser(user: User): Observable<any> {

    return this.http.get<User>(`${this.api}/users/${user.USERID}`);
  }

  //POST: /users (add user to the system and hash store its password on the database)
  userAdd(user: User): Observable<any> {

    return this.http.post<any>(`${this.api}/users`, user)
      .pipe(map(wrapper => wrapper.message))
  }

  //PUT: /users/:userid (updates single user information)
  useredit(user: User): Observable<any> {

    return this.http.put<any>(`${this.api}/users/${user.USERID}`, user)
      .pipe(map(wrapper => wrapper.message))
  }

  //DELETE: /users/:userid (deletes single user from the database)
  userDelete(user: User) {

    return this.http.delete<User[]>(`${this.api}/users/${user.USERID}`);
  }

  //--------------------------------- PASSWORD MANAGEMENT REQUESTS ---------------------------------

  /*PUT: /users/:userid/pwd -> Checks if the USERNAME + USERPASSWORD pair is valid on logon based on the hashed value stored in the database.*/
  userLogin(user: User): Observable<any> {

    return this.http.put<User>(`${this.api}/users/${user.USERID}/pwd`, user, httpOptions);
  }

  //--------------------------------- PASSWORD RESET REQUESTS ---------------------------------

  /*GET: /:id/reset/:guid -> The GUID is generated by the API and the user will access our website with this link to reset its password. 
  The GUID will be checked for validity, if it is valid it will return a User object with only USERID and USERNAME, otherwise the API will return a 404 error.*/
  userCredentialCheck(user: User, GUID): Observable<any> {

    return this.http.get<User>(`${this.api}/${user.USERID}/reset/${GUID}`);
  }

  /* PUT: /:id/reset/ -> Receives an object with the USERID and USEREMAIL to have its password reset. 
  This function will send the user an Email with instructions to reset its password. 
  The object sent to it must be sent in the following form (notice the single quotes around the Email address, they are required): 
  {"USERID":"usr", "USEREMAIL":"'email@me.com'"} */
  userPasswordReset(user: User): Observable<any> {

    return this.http.put<User>(`${this.api}/${user.USERID}/reset`, user, httpOptions);
  }

  /* POST: /:id/reset -> Receives an object with the USERID and USERPASSWORD to have its password reset. 
  It simply sets the selected user's password to the password provided in the object and returns the object with USERPASSWORD set to true. */
  userPasswordChange(user: User): Observable<any> {

    return this.http.post<User>(`${this.api}/${user.USERID}/reset/`, user);
  }

  //--------------------------------- REVIEW REQUESTS ---------------------------------

  // GET: /reviews/:gameid -> Retrieves all stored reviews for a specific game
  gameGetReviews(gameid: String): Observable<any>{

    return this.http.get<any>(`${this.api}/reviews/${gameid}`);
  }

  // GET: /reviews/:gameid -> Retrieves all stored reviews for a specific game
  userGetReviews(userid: String): Observable<any>{

    return this.http.get<any>(`${this.api}/reviews/user/${userid}`);
  }

  // GET: /review/:gameid/:userid -> Retrieves all stored reviews for a specific game
  getReview(gameid: String, userid: String): Observable<any>{

    return this.http.get<any>(`${this.api}/review/${gameid}/${userid}`);
  }

  /* Object blueprint for POST and PUT ->

    const object = {
        USERID: req.params.userid,
        GAMEID: req.params.gameid,
        REVIEWSUMMARY: req.body.REVIEWSUMMARY,
        REVIEWRATING: req.body.REVIEWRATING,
        GAMEPLATFORM: req.body.GAMEPLATFORM
    };
  */

  /* POST: /review/:gameid/:userid -> Receives an object with USERID, GAMEID, REVIEWSUMMARY, 
  REVIEWRATING and GAMEPLATFORM to be posted for the parameters gameid and userid */
  gameReviewAdd(review: any): Observable<any>{

    return this.http.post<any>(`${this.api}/review/${review.GAMEID}/${review.USERID}`, review);
  }

  /* PUT: /review/:gameid/:userid -> Receives an object with USERID, GAMEID, REVIEWSUMMARY, 
  REVIEWRATING and GAMEPLATFORM to be updated for the parameters gameid and userid */
  gameReviewEdit(review: any): Observable<any>{

    return this.http.put<any>(`${this.api}/review/${review.GAMEID}/${review.USERID}`, review);
  }

  /* DELETE: /review/:gameid/:userid -> Receives an object with GAMEID and USERID for a review to be deleted from the database */
  gameReviewDelete(review: any): Observable<any>{

    return this.http.delete<any>(`${this.api}/review/${review.GAMEID}/${review.USERID}`);
  }

  //--------------------------------- LIBRARY MANAGEMENT ---------------------------------

  // GET: /library/:userid -> Retrieves all stored games associated with a user library
  getUserLibrary(userid: String): Observable<any>{

    return this.http.get<any>(`${this.api}/library/${userid}`);
  }

  // PUT: /library/:userid/:gameid -> Associates a gameid to a user's library
  addToUserLibrary(userid: String, gameid: String): Observable<any>{

    const lib = {
      USERID : userid,
      GAMEID : gameid
    }

    return this.http.put<any>(`${this.api}/library/${lib.USERID}/${lib.GAMEID}`, lib);
  }

  // DELETE: /library/:userid/:gameid -> Removes a gameid from a user's library
  removeFromUserLibrary(userid: String, gameid: String): Observable<any>{

    return this.http.delete<any>(`${this.api}/library/${userid}/${gameid}`);
  }

  //--------------------------------- REGISTRATION TOOLS ---------------------------------

  /* GET: /register/get-email/:email -> Returns true if the e-mail passed as parameter already 
  exists in the DB, false otherwise */
  checkEmailDB(email: String): Observable<any> {

    return this.http.get<any>(`${this.api}/register/get-email/${email}`);
  }

  /* GET: /register/get-userid/:userid -> Returns true if the userid passed as parameter already 
  exists in the DB, false otherwise */
  checkUserIDDB(userid: String): Observable<any> {

    return this.http.get<any>(`${this.api}/register/get-userid/${userid}`);
  }

  //--------------------------------- TAG FUNCTIONALITY ---------------------------------

  // GET: /tag/:tagid/:userid -> Returns all games related to a tag in a user's library
  getGamesForTag(userid: String, tagid: String): Observable<any>{

    return this.http.get<any>(`${this.api}/tag/${tagid}/${userid}`);
  }

  // DELETE: /tag/:tagid/:userid -> Removes a tag from a user's library
  removeTag(userid: String, tagid: String): Observable<any>{

    return this.http.delete<any>(`${this.api}/tag/${tagid}/${userid}`);
  }

  // POST: /tag -> Receives an object with USERID, GAMEID, and TAGID to be added to a user's library
  addTag(tag: any): Observable<any>{

    return this.http.post<any>(`${this.api}/tag`, tag);
  }
}

  